apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
#  storageClassName: standard
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  nfs:
  hostPath:
    path: /mnt/nfs_share/
#    server: 167.71.228.6
