apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
#  storageClassName: standard
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4050Mi
